// Concatenates the source CSS files in styles/ into the shipped styles.css.
// Mirrors the TaskNotes CSS build (styles/ source of truth -> single styles.css).
import { readFileSync, writeFileSync } from "node:fs";
import process from "node:process";

const CSS_FILES = [
	"styles/variables.css", // design tokens (load first)
	"styles/task-card-note-widget.css", // note widget container
	"styles/task-card.css", // BEM task card look
	"styles/widget.css", // header / date / empty / panel
	"styles/modal.css", // task modal: status picker, projects, label icons
];

const HEADER = `/* DayTasks styles — generated by build-css.mjs. Do not edit directly.
   Edit the source files in styles/ and re-run "npm run build-css". */\n`;

function buildCss() {
	let combined = HEADER;
	for (const file of CSS_FILES) {
		const content = readFileSync(file, "utf8");
		combined += `\n/* ===== ${file.split("/").pop().toUpperCase()} ===== */\n`;
		combined += content + "\n";
		console.log(`[ok] included ${file}`);
	}
	writeFileSync("styles.css", combined);
	console.log(`[ok] wrote styles.css (${combined.split("\n").length} lines)`);
}

try {
	buildCss();
} catch (error) {
	console.error("[error] build-css failed:", error.message);
	process.exit(1);
}
